---
title: "HW 06 - Legos"
author: "Raya Shelashska,"
date: "July 19, 2022"
output: github_document
editor_options: 
  chunk_output_type: console
---

## Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse)
library(dsbox)
```

## Exercises

### Exercise 1

Three the most common names of purchasers are Jackson, Jacob, and Joseph.
```{r top-3-names}
lego_sales %>%
  count(first_name, sort = TRUE) %>%
  top_n(3)
```

### Exercise 2

Three the most common themes of Lego sets: Star Wars, Nexo Knights, and Gear.
```{r top-3-themes}
lego_sales %>%
  count(theme, sort = TRUE) %>%
  top_n(3)
```


### Exercise 3

```{r top-3-subthemes-1}
lego_sales %>%
  filter(theme == "Star Wars") %>%
  count(subtheme, sort = TRUE) %>%
  top_n(3)
```

```{r top-3-subthemes-2}
lego_sales %>%
  filter(theme == "SNexo Knights") %>%
  count(subtheme, sort = TRUE) %>%
  top_n(3)
```

```{r top-3-subthemes-3}
lego_sales %>%
  filter(theme == "Gear") %>%
  count(subtheme, sort = TRUE) %>%
  top_n(3)
```

### Exercise 4

```{r age_grouping}
lego_sales <- lego_sales %>%
  mutate(age_group = case_when(
    age <= 18 ~ "18 and under",
    age > 18 & age <= 25 ~ "19 - 25",
    age > 25 & age <= 35 ~ "26 - 35",
    age > 35 & age <= 50 ~ "36 - 50", 
    age > 50 ~ "51 and over"
    ))

```


### Exercise 5

...

### Exercise 6

...

### Exercise 7

...

### Exercise 8

...

### Exercise 9

...
